// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotDefteriApi.Data;

#nullable disable

namespace NotDefteriApi.Data.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20240223063804_Ilk")]
    partial class Ilk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotDefteriApi.Data.Not", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Baslik = "Alışveriş Listesi",
                            Icerik = "Süt, ekmek, yumurta ve elma alınacak."
                        },
                        new
                        {
                            Id = 2,
                            Baslik = "Kitap Önerileri",
                            Icerik = "1. Sapiens, 2. Kürk Mantolu Madonna, 3. Fahrenheit 451"
                        },
                        new
                        {
                            Id = 3,
                            Baslik = "Haftalık Hedefler",
                            Icerik = "Haftada 3 gün spor yapmak, her gün 2 litre su içmek ve erken yatmak."
                        },
                        new
                        {
                            Id = 4,
                            Baslik = "Toplantı Notları",
                            Icerik = "Projede son durum değerlendirmesi yapılacak, yeni görev dağılımları konuşulacak."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
